const ResumeApi = [
    {
      id: 1,
      category: "education",
      year: "UNIVERSITE DE GRENOBLE 1 (2001-2002) ",
      title: "DAEU B équivalent baccalauréat Scientifique.",
      desc: "Equivalence au canada : DES ",
      rate: "4.30/5",
    },
    {
      id: 2,
      category: "education",
      year: "CNED  (2003 - 2005) ",
      title: "BTS Informatique de Gestion.",
      desc: "Equivalence au canada : DEC",
      rate: "4.50/5",
    },
    {
      id: 3,
      category: "education",
      year: "STUDI (2022)",
      title: "Graduate fullstack OPTION FLUTTER ",
      desc: "Equivalence au canada : BACCALAUREAT",
      rate: "4.80/5 ",
    },
    {
      id: 4,
      category: "education",
      year: "STUDI (2022-2023)",
      title: "BACHELOR fullstack OPTION python ",
      desc: "Equivalence au canada : BACCALAUREAT",
      rate: "4.80/5 ",
    },
    {
      id: 5,
      category: "experience",
      year: "PI-Service (2005 - 2010) ",
      title: "Administrateur systèmes & réseaux",
      desc: "Administrateur Système et réseaux, pour l'exploitation bureautique des technologies Microsoft office",
      rate: "4.70/5 ",
    },
    {
      id: 6,
      category: "experience",
      year: "Wipit (2011 - 2018) ",
      title: "Ingénieur Systèmes & réseaux ",
      desc: "Ingénieur Système et réseaux, Ingénieur sécurité, sauvegarde.",
      rate: "4.95/5 ",
    },
    {
      id: 7,
      category: "experience",
      year: "Développeur freelance (2019 - 2022) ",
      title: "Diploma in Computer Science",
      desc: "Conception & développement d'application web et mobile. Développement & maintien de site vitrine et E-commerce. Gestion de projet.",
      rate: "5.00/5 ",
    },
  ]
  
  export default ResumeApi